### ISSUE TITLE
Guess the Key - Fails to Connect to Mongo

### ISSUE THREAD

**Issue by torque59** [digininja/nosqlilab#3]
Just observed that guess_the_key.php fails to connect to mongo.

Change line 47 from 

`$mongo_driver = new MongoDB\Driver\Manager;` to

`$mongo_driver = new MongoDB\Driver\Manager("mongodb://mongo:27017");`

Works for me.

**Comment by digininja** [comment]
Odd as no one has commented on it not working for them but I don't see that adding it would be a problem. Might be best done as a config option with the driver coming from a file or constant. Let me check that adding it doesn't break it in my set up and if it doesn't I'll add it in, probably next week. If you don't hear back prod me about it.

**Comment by torque59** [comment]
Actually this was happening when ran it with the docker setup given.

**Comment by paralax** [comment]
The docker setup doesn't touch that file so off the bat I don't think it's an issue introduced there. It looks like it's a missing connection string originally. 

I wrote the docker setup scripts.

**Comment by paralax** [comment]
just to close the loop: 

> i did some digging last night and noticed that without any args the MongoDB constructor assumes localhost, which barfs in a Docker env. by being explicit about localhost it should work in Vagrant where both Apache-PHP and Mongo are installed in one box and work in Docker where that's two separate containers. the Dockerfile replaces the location in this one, same as others.

this WAS an issue i introduced and an oversight during my development and testing.

thank you for noticing.
